version: "3"
services:
  mongo1:
    container_name: mongo_31415926_1
    image: mongo:latest
    ports:
      - "30001:27017"
    restart: always
    networks:
      - cluster_network
    volumes:
      - ./:/opt
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rest-replica-set" ]

  mongo2:
    container_name: mongo_31415926_2
    image: mongo:latest
    ports:
      - "30002:27017"
    restart: always
    networks:
      - cluster_network
    volumes:
      - ./:/opt
    depends_on:
      - mongo1
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rest-replica-set" ]

  mongo3:
    container_name: mongo_31415926_3
    image: mongo:latest
    ports:
      - "30003:27017"
    restart: always
    networks:
      - cluster_network
    volumes:
      - ./:/opt
    depends_on:
      - mongo2
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rest-replica-set" ]

  config:
    hostname: config_container
    image: mongo:latest
    restart: "no"
    networks:
      - cluster_network
    volumes:
      - ./:/opt
    depends_on:
      - mongo3
    command: sh /opt/configure-replica.sh
    #command: ["/bin/bash", "-c", "sleep infinity"]

  server:
    hostname: app_server
    build: .
    restart: always
    networks:
      - cluster_network
    volumes:
      - ./server:/opt
    ports:
      - "8000:8000"

networks:
    cluster_network: